set_property PACKAGE_PIN AD23  [get_ports hdmi_in_clk]
set_property PACKAGE_PIN AD25  [get_ports {hdmi_in_data[0]}]
set_property PACKAGE_PIN AD24  [get_ports {hdmi_in_data[1]}]
set_property PACKAGE_PIN AC24  [get_ports {hdmi_in_data[2]}]
set_property PACKAGE_PIN AC23  [get_ports {hdmi_in_data[3]}]
set_property PACKAGE_PIN AB26  [get_ports {hdmi_in_data[4]}]
set_property PACKAGE_PIN AC26  [get_ports {hdmi_in_data[5]}]
set_property PACKAGE_PIN AB24  [get_ports {hdmi_in_data[6]}]
set_property PACKAGE_PIN AA24  [get_ports {hdmi_in_data[7]}]
set_property PACKAGE_PIN AB25  [get_ports {hdmi_in_data[8]}]
set_property PACKAGE_PIN AA25  [get_ports {hdmi_in_data[9]}]
set_property PACKAGE_PIN AE23  [get_ports {hdmi_in_data[10]}]
set_property PACKAGE_PIN AF23  [get_ports {hdmi_in_data[11]}]
set_property PACKAGE_PIN AA23  [get_ports {hdmi_in_data[12]}]
set_property PACKAGE_PIN AA22  [get_ports {hdmi_in_data[13]}]
set_property PACKAGE_PIN AF20  [get_ports {hdmi_in_data[14]}]
set_property PACKAGE_PIN AF19  [get_ports {hdmi_in_data[15]}]
set_property PACKAGE_PIN W19   [get_ports {hdmi_in_data[16]}]
set_property PACKAGE_PIN W18   [get_ports {hdmi_in_data[17]}]
set_property PACKAGE_PIN AA19  [get_ports {hdmi_in_data[18]}]
set_property PACKAGE_PIN AB19  [get_ports {hdmi_in_data[19]}]
set_property PACKAGE_PIN AD19  [get_ports {hdmi_in_data[20]}]
set_property PACKAGE_PIN AD18  [get_ports {hdmi_in_data[21]}]
set_property PACKAGE_PIN Y20   [get_ports {hdmi_in_data[22]}]
set_property PACKAGE_PIN W20   [get_ports {hdmi_in_data[23]}]
set_property PACKAGE_PIN AD26   [get_ports hdmi_in_de]
set_property PACKAGE_PIN AF24   [get_ports hdmi_in_hs]
set_property PACKAGE_PIN AA18   [get_ports {hdmi_rstn_tri_o[0]}]
set_property PACKAGE_PIN AF25   [get_ports hdmi_in_vs]
set_property PACKAGE_PIN AE26   [get_ports hdmi_in_i2c_scl_io]
set_property PACKAGE_PIN AE25   [get_ports hdmi_in_i2c_sda_io]


set_property PULLUP true [get_ports hdmi_in_i2c_scl_io]
set_property PULLUP true [get_ports hdmi_in_i2c_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_in_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_vs]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_rstn_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_i2c_sda_io]

set_property IOB TRUE [get_ports {hdmi_in_data[*]}]
set_property IOB TRUE [get_ports hdmi_in_de]
set_property IOB TRUE [get_ports hdmi_in_hs]
set_property IOB TRUE [get_ports hdmi_in_vs]

set_property DRIVE 12 [get_ports {hdmi_in_data[*]}]
set_property DRIVE 16 [get_ports hdmi_in_clk]
set_property DRIVE 12 [get_ports hdmi_in_de]
set_property DRIVE 12 [get_ports hdmi_in_hs]

create_clock -period 6.734 -name hdmi_in_clk -waveform {0.000 3.367} [get_ports hdmi_in_clk]
set_input_delay -clock [get_clocks hdmi_in_clk] -min -add_delay 2.500 [get_ports {hdmi_in_data[*]}]
set_input_delay -clock [get_clocks hdmi_in_clk] -max -add_delay 3.500 [get_ports {hdmi_in_data[*]}]
set_input_delay -clock [get_clocks hdmi_in_clk] -min -add_delay 2.500 [get_ports hdmi_in_de]
set_input_delay -clock [get_clocks hdmi_in_clk] -max -add_delay 3.500 [get_ports hdmi_in_de]
set_input_delay -clock [get_clocks hdmi_in_clk] -min -add_delay 2.500 [get_ports hdmi_in_hs]
set_input_delay -clock [get_clocks hdmi_in_clk] -max -add_delay 3.500 [get_ports hdmi_in_hs]
set_input_delay -clock [get_clocks hdmi_in_clk] -min -add_delay 2.500 [get_ports hdmi_in_vs]
set_input_delay -clock [get_clocks hdmi_in_clk] -max -add_delay 3.500 [get_ports hdmi_in_vs]