set_property PACKAGE_PIN Y12 	[get_ports {ADC_PORT_ad7606_os[0]}]
set_property PACKAGE_PIN Y11 	[get_ports {ADC_PORT_ad7606_os[1]}]
set_property PACKAGE_PIN AB12 	[get_ports {ADC_PORT_ad7606_os[2]}]
set_property PACKAGE_PIN AC11 	[get_ports ADC_PORT_ad7606_convstab]
set_property PACKAGE_PIN AA13 	[get_ports ADC_PORT_ad7606_reset]
set_property PACKAGE_PIN AA12 	[get_ports ADC_PORT_ad7606_rd]
set_property PACKAGE_PIN AE11 	[get_ports ADC_PORT_ad7606_cs]
set_property PACKAGE_PIN AF10 	[get_ports ADC_PORT_ad7606_busy]
set_property PACKAGE_PIN AD13 	[get_ports ADC_PORT_ad7606_first_data]
set_property PACKAGE_PIN AD11  	[get_ports {ADC_PORT_ad7606_data[0]}]
set_property PACKAGE_PIN AC12  	[get_ports {ADC_PORT_ad7606_data[1]}]
set_property PACKAGE_PIN AA14  	[get_ports {ADC_PORT_ad7606_data[2]}]
set_property PACKAGE_PIN AA15  	[get_ports {ADC_PORT_ad7606_data[3]}]
set_property PACKAGE_PIN Y10	[get_ports {ADC_PORT_ad7606_data[4]}]
set_property PACKAGE_PIN AA10  	[get_ports {ADC_PORT_ad7606_data[5]}]
set_property PACKAGE_PIN AE15  	[get_ports {ADC_PORT_ad7606_data[6]}]
set_property PACKAGE_PIN AE16  	[get_ports {ADC_PORT_ad7606_data[7]}]
set_property PACKAGE_PIN W15	[get_ports {ADC_PORT_ad7606_data[8]}]
set_property PACKAGE_PIN W16	[get_ports {ADC_PORT_ad7606_data[9]}]
set_property PACKAGE_PIN AC16   [get_ports {ADC_PORT_ad7606_data[10]}]
set_property PACKAGE_PIN AC17   [get_ports {ADC_PORT_ad7606_data[11]}]
set_property PACKAGE_PIN AD10   [get_ports {ADC_PORT_ad7606_data[12]}]
set_property PACKAGE_PIN AE10   [get_ports {ADC_PORT_ad7606_data[13]}]
set_property PACKAGE_PIN AE12   [get_ports {ADC_PORT_ad7606_data[14]}]
set_property PACKAGE_PIN AF12   [get_ports {ADC_PORT_ad7606_data[15]}]



set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_convstab]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_rd]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_cs]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_busy]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_PORT_ad7606_os[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_PORT_ad7606_data[*]}]

