set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[0]}]
set_property PACKAGE_PIN AB15 [get_ports {leds_tri_o[0]}]
set_property PACKAGE_PIN AB14 [get_ports {leds_tri_o[1]}]
set_property PACKAGE_PIN AF13 [get_ports {leds_tri_o[2]}]
set_property PACKAGE_PIN AE13 [get_ports {leds_tri_o[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {keys_tri_i[0]}]
set_property PACKAGE_PIN AF15 [get_ports {keys_tri_i[0]}]
