# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Y:/project/zynq_ip_repo/alinx/ov5640_ip/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf.xci
# IP: The module: 'cmos_in_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/project/zynq_ip_repo/alinx/ov5640_ip/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf/cmos_in_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmos_in_buf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: y:/project/zynq_ip_repo/alinx/ov5640_ip/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmos_in_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: Y:/project/zynq_ip_repo/alinx/ov5640_ip/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf.xci
# IP: The module: 'cmos_in_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/project/zynq_ip_repo/alinx/ov5640_ip/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf/cmos_in_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmos_in_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: y:/project/zynq_ip_repo/alinx/ov5640_ip/alinx_ov5640.srcs/sources_1/ip/cmos_in_buf/cmos_in_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmos_in_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
