set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_p]
set_property PACKAGE_PIN C8 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
############## AN871 LCD##################
set_property PACKAGE_PIN Y12 [get_ports {lcd_pwm}]
set_property PACKAGE_PIN AA12 [get_ports {lcd_hs}]
set_property PACKAGE_PIN AA13 [get_ports {lcd_vs}]
set_property PACKAGE_PIN AF10 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN AE11 [get_ports {lcd_de}]
set_property PACKAGE_PIN AC13 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN AD13	[get_ports {lcd_b[7]}]
set_property PACKAGE_PIN Y13	[get_ports {lcd_b[4]}]
set_property PACKAGE_PIN W13 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN AD11 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN AC12 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN AA14 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN AA15	[get_ports {lcd_b[1]}]
set_property PACKAGE_PIN Y10  [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN AA10  [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN AE15  [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN AE16 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN W15 	[get_ports {lcd_g[2]}]
set_property PACKAGE_PIN W16  [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN AC16 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN AC17 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN AD10  [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN AE10  [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN AE12 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN AF12 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN AB10 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN AB11 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN AB16 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN AB17 	[get_ports {lcd_r[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_pwm}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[*]}]

