set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_clk_p]
set_property PACKAGE_PIN C8 [get_ports sys_clk_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_clk_p]

set_property PACKAGE_PIN C13 [get_ports {mdio_mdc          }]
set_property PACKAGE_PIN D13 [get_ports {mdio_mdio_io      }]
set_property PACKAGE_PIN A14 [get_ports {phy_rst_n         }]
set_property PACKAGE_PIN G14  [get_ports {rgmii_rxc         }]
set_property PACKAGE_PIN F14  [get_ports {rgmii_rx_ctl      }]
set_property PACKAGE_PIN A13  [get_ports {rgmii_rd[0]       }]
set_property PACKAGE_PIN A12  [get_ports {rgmii_rd[1]       }]
set_property PACKAGE_PIN B12  [get_ports {rgmii_rd[2]       }]
set_property PACKAGE_PIN C12  [get_ports {rgmii_rd[3]       }]
set_property PACKAGE_PIN C11  [get_ports {rgmii_txc         }]
set_property PACKAGE_PIN B11  [get_ports {rgmii_tx_ctl      }]
set_property PACKAGE_PIN E10  [get_ports {rgmii_td[0]       }]
set_property PACKAGE_PIN D10  [get_ports {rgmii_td[1]       }]
set_property PACKAGE_PIN F13  [get_ports {rgmii_td[2]       }]
set_property PACKAGE_PIN E13  [get_ports {rgmii_td[3]       }]

set_property IOSTANDARD LVCMOS18 [get_ports {mdio_mdc          }]
set_property IOSTANDARD LVCMOS18 [get_ports {mdio_mdio_io      }]
set_property IOSTANDARD LVCMOS18 [get_ports {phy_rst_n         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxc         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rx_ctl      }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[0]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[1]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[2]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[3]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txc         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_tx_ctl      }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[0]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[1]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[2]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[3]       }]